In [1]:
import numpy as np

# Start = 2, Stop = 50, Step Size = 3
arr = np.arange(2, 50, 3)

In [2]:
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [6]:
import numpy as np

a=[]
print("Enter 5 elements:")
for i in range(1,6):
    b=int(input("Enter element:"))
    a.append(b)
c=[]
print("Enter 5 elements:")
for i in range(1,6):
    d=int(input("Enter element:"))
    c.append(d)
arr1 = np.array(a)
arr2 = np.array(c)
fin_arr=np.concatenate((a, c), axis=None)

def selection_sort(fin_arr):
    for i in range(len(fin_arr)):
        swap = i + np.argmin(fin_arr[i:])
        (fin_arr[i], fin_arr[swap]) = (fin_arr[swap], fin_arr[i])
    return fin_arr

selection_sort(fin_arr)

Enter 5 elements:
Enter element:12
Enter element:56
Enter element:98
Enter element:41
Enter element:35
Enter 5 elements:
Enter element:62
Enter element:27
Enter element:55
Enter element:30
Enter element:22


array([12, 22, 27, 30, 35, 41, 55, 56, 62, 98])

In [7]:
import numpy as np

a_1d = np.arange(3)
print(a_1d)
# [0 1 2]

a_2d = np.arange(12).reshape((3, 4))
print(a_2d)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)
# [[[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]
# 
#  [[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]]

[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
print(a_1d.ndim)
# 1

print(type(a_1d.ndim))
# <class 'int'>

print(a_2d.ndim)
# 2

print(a_3d.ndim)
# 3

1
<class 'int'>
2
3


In [9]:
print(a_1d.size)
# 3

print(type(a_1d.size))
# <class 'int'>

print(a_2d.size)
# 12

print(a_3d.size)
# 24

3
<class 'int'>
12
24


In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]


In [12]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)

# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

# Modify the 2D numpy array (View object)
arr_2d[0][0] = 22
print('1D Numpy array:')
print(arr)
print('2D Numpy array:')
print(arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
1D Numpy array:
[22  1  2  3  4  5  6  7  8  9]
2D Numpy array:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]


In [13]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [14]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [1]:
# import library 
import pandas as pd 
  
# create a Dataframe 
df = pd.DataFrame({  
  'height' : [165, 165, 164,  
              158, 167, 160, 
              158, 165], 
    
  'weight' : [63.5, 64, 63.5, 
              54, 63.5, 62, 
              64, 64], 
    
  'age' : [20, 22, 22,  
           21, 23, 22, 
           20, 21]}, 
    
   index = ['Steve', 'Ria', 'Nivi',  
            'Jane', 'Kate', 'Lucy', 
            'Ram', 'Niki']) 
  
# show the Dataframe 
df

height  weight  age
Steve     165    63.5   20
Ria       165    64.0   22
Nivi      164    63.5   22
Jane      158    54.0   21
Kate      167    63.5   23
Lucy      160    62.0   22
Ram       158    64.0   20
Niki      165    64.0   21